server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imagineat
    username: postgres
    password: root
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/imagineat
    user: postgres
    password: root
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false # fix hibernate bug with a popped up error
  data:
    rest:
      base-path: /api
      detection-strategy: default
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  servlet:
    multipart:
      # Enable multipart uploads
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB

# File Storage Properties
file:
  # All files uploaded through the REST API will be stored in this directory
  upload-dir: /upload-dir